name:                FibPseudoprime
version:             0.1.0.0
github:              "ensj/FibPseudoprime"
license:             BSD3
author:              "ensj, smashalkar"
maintainer:          "ensjtrans@gmail.com"
copyright:           "2021 ensjtrans"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/FibPseudoprime#readme>

dependencies:
- base >= 4.7 && < 5
- arithmoi
- hspec
- QuickCheck
- criterion
- text
- random
- stm
- deepseq

library:
  source-dirs: src

executables:
  FibPseudoprime-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FibPseudoprime

tests:
  FibPseudoprime-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FibPseudoprime
